name: CLA Bot Test

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  issues: write
  statuses: write

jobs:
  cla:
    runs-on: ubuntu-latest

    steps:
      - uses: rajnishtiwari7/cla-bot@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          signatures-owner: rajnishtiwari7
          signatures-repo: cla-signatures
          signatures-path: signatures/cla.json

          app-id: ${{ secrets.CLA_APP_ID }}
          app-private-key: ${{ secrets.CLA_APP_PRIVATE_KEY }}

          cla-document-url: https://github.com/rajnishtiwari7/cla-testing/blob/main/README.md

          allowlist: dependabot[bot]
